//! Build script: generate one `#[test]` function per corpus snippet.
//!
//! Reads:
//!   - `tests/corpus/*.txt`                  (tree-sitter corpus)
//!   - `tests/corpus/juliasyntax_parser.jl`  (JuliaSyntax.jl corpus)
//!   - `tests/corpus/expectations.toml`      (snippets expected to fail)
//!
//! Emits:
//!   - `$OUT_DIR/roundtrip_generated.rs`
//!   - `$OUT_DIR/ast_equivalence_generated.rs`
//!
//! The test wrappers include those via `include!(concat!(env!("OUT_DIR"), ...))`.

use serde::Deserialize;
use std::collections::HashSet;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

// ─── Expectations schema ────────────────────────────────────────────

#[derive(Debug, Default, Deserialize)]
struct Expectations {
    #[serde(default)]
    juliasyntax: Vec<JuliaSyntaxExpectation>,
    #[serde(default)]
    roundtrip: Vec<RoundtripExpectation>,
}

#[derive(Debug, Deserialize)]
struct JuliaSyntaxExpectation {
    line: usize,
    status: String, // "grammar_gap" | "format_error" | "ast_mismatch"
    #[serde(default)]
    note: String,
}

#[derive(Debug, Deserialize)]
struct RoundtripExpectation {
    file: String,
    name: String,
    #[serde(default)]
    note: String,
}

#[derive(Debug, Deserialize)]
struct LocalizedGaps {
    #[serde(default)]
    snippet: Vec<LocalizedSnippet>,
}

#[derive(Debug, Deserialize)]
struct LocalizedSnippet {
    code: String,
    #[serde(default)]
    js_sexp: String,
    #[serde(default)]
    origin: String,
}

// ─── Entry point ────────────────────────────────────────────────────

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let corpus_dir = PathBuf::from(&manifest_dir).join("tests/corpus");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    let expectations_path = corpus_dir.join("expectations.toml");
    rerun_if_changed(&expectations_path);
    let expectations: Expectations = if expectations_path.exists() {
        let raw = fs::read_to_string(&expectations_path).expect("read expectations.toml");
        toml::from_str(&raw).expect("parse expectations.toml")
    } else {
        Expectations::default()
    };

    generate_roundtrip(&corpus_dir, &out_dir, &expectations);
    generate_ast_equivalence(&corpus_dir, &out_dir, &expectations);
    generate_localized_gaps(&corpus_dir, &out_dir);
}

fn rerun_if_changed(path: &Path) {
    println!("cargo:rerun-if-changed={}", path.display());
}

// ─── Roundtrip: tree-sitter corpus ──────────────────────────────────

const TS_CORPUS_FILES: &[&str] = &[
    "collections",
    "definitions",
    "expressions",
    "literals",
    "operators",
    "statements",
];

fn generate_roundtrip(corpus_dir: &Path, out_dir: &Path, exp: &Expectations) {
    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs — do not edit.\n\n");

    let exp_set: HashSet<(&str, &str)> = exp
        .roundtrip
        .iter()
        .map(|e| (e.file.as_str(), e.name.as_str()))
        .collect();
    let exp_map: std::collections::HashMap<(&str, &str), &str> = exp
        .roundtrip
        .iter()
        .map(|e| ((e.file.as_str(), e.name.as_str()), e.note.as_str()))
        .collect();

    let mut used_names: HashSet<String> = HashSet::new();
    let mut used_expectations: HashSet<(String, String)> = HashSet::new();

    for file in TS_CORPUS_FILES {
        let path = corpus_dir.join(format!("{file}.txt"));
        rerun_if_changed(&path);
        let corpus = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        for (name, code) in extract_treesitter(&corpus) {
            let ident = unique_ident(&mut used_names, &format!("rt_{file}_{}", sanitize(&name)));
            let expected = exp_set.contains(&(*file, name.as_str()));
            if expected {
                used_expectations.insert((file.to_string(), name.clone()));
            }
            let note = exp_map
                .get(&(*file, name.as_str()))
                .copied()
                .unwrap_or("");

            out.push_str(&format!("#[test]\nfn {ident}() {{\n"));
            out.push_str(&format!("    const CODE: &str = {};\n", rust_string(&code)));
            if expected {
                out.push_str(&format!(
                    "    common::expect_roundtrip_regression(CODE, {});\n",
                    rust_string(note)
                ));
            } else {
                out.push_str("    common::assert_roundtrip_clean(CODE);\n");
            }
            out.push_str("}\n\n");
        }
    }

    // Sanity check: every expectation refers to a real corpus entry.
    for entry in &exp.roundtrip {
        if !used_expectations.contains(&(entry.file.clone(), entry.name.clone())) {
            panic!(
                "expectations.toml: roundtrip entry {{ file = {:?}, name = {:?} }} does not match any corpus snippet",
                entry.file, entry.name
            );
        }
    }

    let dest = out_dir.join("roundtrip_generated.rs");
    fs::write(&dest, out).expect("write roundtrip_generated.rs");
}

fn extract_treesitter(corpus: &str) -> Vec<(String, String)> {
    let mut snippets = Vec::new();
    for section in corpus.split("\n---\n") {
        let lines: Vec<&str> = section.lines().collect();
        let mut header_end = None;
        for (i, line) in lines.iter().enumerate().rev() {
            if line.starts_with("====") && i >= 2 && lines[i - 2].starts_with("====") {
                header_end = Some(i);
                break;
            }
        }
        if let Some(end_idx) = header_end {
            let name = lines[end_idx - 1].to_string();
            let code = lines[end_idx + 1..].join("\n");
            if !code.trim().is_empty() {
                snippets.push((name, code));
            }
        }
    }
    snippets
}

// ─── AST equivalence: JuliaSyntax.jl corpus ─────────────────────────

fn generate_ast_equivalence(corpus_dir: &Path, out_dir: &Path, exp: &Expectations) {
    let path = corpus_dir.join("juliasyntax_parser.jl");
    rerun_if_changed(&path);
    let corpus = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let snippets = extract_juliasyntax(&corpus);

    let exp_by_line: std::collections::HashMap<usize, &JuliaSyntaxExpectation> =
        exp.juliasyntax.iter().map(|e| (e.line, e)).collect();
    let mut used_expectations: HashSet<usize> = HashSet::new();

    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs — do not edit.\n\n");

    for s in &snippets {
        // Intentional errors (JuliaSyntax itself expects an error) are of no
        // interest to the formatter; skip them entirely.
        if is_intentional_error(&s.expected) {
            continue;
        }

        let suffix_status = exp_by_line.get(&s.line).map(|e| e.status.as_str());
        let suffix = suffix_status.map(|s| format!("_{s}")).unwrap_or_default();
        let ident = format!("ast_line_{:04}{}", s.line, suffix);
        let note = exp_by_line
            .get(&s.line)
            .map(|e| e.note.as_str())
            .unwrap_or("");

        out.push_str(&format!("#[test]\nfn {ident}() {{\n"));
        out.push_str(&format!("    const CODE: &str = {};\n", rust_string(&s.code)));

        match suffix_status {
            None => {
                out.push_str("    common::assert_ast_equivalent(CODE);\n");
            }
            Some("grammar_gap") => {
                used_expectations.insert(s.line);
                out.push_str(&format!(
                    "    common::expect_grammar_gap(CODE, {});\n",
                    rust_string(note)
                ));
            }
            Some("format_error") => {
                used_expectations.insert(s.line);
                out.push_str(&format!(
                    "    common::expect_format_error(CODE, {});\n",
                    rust_string(note)
                ));
            }
            Some("ast_mismatch") => {
                used_expectations.insert(s.line);
                out.push_str(&format!(
                    "    common::expect_ast_mismatch(CODE, {});\n",
                    rust_string(note)
                ));
            }
            Some(other) => panic!(
                "expectations.toml: unknown juliasyntax status {other:?} at line {}",
                s.line
            ),
        }
        out.push_str("}\n\n");
    }

    // Sanity check: every expectation refers to a real snippet we emitted a
    // test for. Protects against typos / stale line numbers.
    for entry in &exp.juliasyntax {
        if !used_expectations.contains(&entry.line) {
            panic!(
                "expectations.toml: juliasyntax entry for line {} does not match any extracted snippet \
                 (or the snippet is an intentional error, which cannot be classified further)",
                entry.line
            );
        }
    }

    let dest = out_dir.join("ast_equivalence_generated.rs");
    fs::write(&dest, out).expect("write ast_equivalence_generated.rs");
}

struct JsSnippet {
    line: usize,
    code: String,
    expected: String,
}

fn is_intentional_error(expected: &str) -> bool {
    expected.to_lowercase().contains("error")
}

fn extract_juliasyntax(corpus: &str) -> Vec<JsSnippet> {
    let mut snippets = Vec::new();
    for (line_num, line) in corpus.lines().enumerate() {
        let trimmed = line.trim();
        if trimmed.is_empty()
            || trimmed.starts_with('#')
            || trimmed.starts_with(']')
            || trimmed.starts_with('[')
            || trimmed.starts_with("tests")
            || trimmed.starts_with("JuliaSyntax")
            || trimmed.starts_with("with_version")
            || trimmed.starts_with("function")
            || trimmed.starts_with("end")
            || trimmed.starts_with("PARSE_ERROR")
            || trimmed.starts_with("\"\"\"")
            || trimmed.starts_with("parsestmt")
        {
            continue;
        }

        let Some(arrow_pos) = trimmed.find("=>") else {
            continue;
        };
        let lhs = trimmed[..arrow_pos].trim();
        let rhs = trimmed[arrow_pos + 2..].trim();
        if rhs.starts_with("PARSE_ERROR") || rhs.starts_with("r\"") {
            continue;
        }

        let code = if lhs.starts_with('"') {
            extract_julia_string(lhs)
        } else if lhs.starts_with("((") {
            if let Some(last_quote) = lhs.rfind("\", \"").or_else(|| lhs.rfind("), \"")) {
                let rest = &lhs[last_quote..];
                rest.find('"').and_then(|start| extract_julia_string(&rest[start..]))
            } else {
                None
            }
        } else {
            None
        };

        if let Some(code) = code {
            if !code.is_empty() {
                snippets.push(JsSnippet {
                    line: line_num + 1,
                    code,
                    expected: rhs.to_string(),
                });
            }
        }
    }
    snippets
}

fn extract_julia_string(s: &str) -> Option<String> {
    let s = s.trim();
    if !s.starts_with('"') {
        return None;
    }
    let mut chars = s[1..].chars();
    let mut result = String::new();
    while let Some(c) = chars.next() {
        match c {
            '"' => return Some(result),
            '\\' => {
                if let Some(esc) = chars.next() {
                    match esc {
                        'n' => result.push('\n'),
                        't' => result.push('\t'),
                        '\\' => result.push('\\'),
                        '"' => result.push('"'),
                        '$' => result.push('$'),
                        'r' => result.push('\r'),
                        '0' => result.push('\0'),
                        other => {
                            result.push('\\');
                            result.push(other);
                        }
                    }
                }
            }
            other => result.push(other),
        }
    }
    None
}

// ─── Localized gaps: bisected real-world parse failures ─────────────

fn generate_localized_gaps(corpus_dir: &Path, out_dir: &Path) {
    let path = corpus_dir.join("localized_gaps.toml");
    rerun_if_changed(&path);

    let mut out = String::from("// Auto-generated by build.rs — do not edit.\n\n");

    if path.exists() {
        let raw = fs::read_to_string(&path).expect("read localized_gaps.toml");
        let data: LocalizedGaps = toml::from_str(&raw).expect("parse localized_gaps.toml");
        for (i, s) in data.snippet.iter().enumerate() {
            let ident = format!("ts_gap_{:04}", i + 1);
            out.push_str(&format!("#[test]\nfn {ident}() {{\n"));
            if !s.js_sexp.is_empty() {
                out.push_str(&format!("    // JuliaSyntax: {}\n", escape_line_comment(&s.js_sexp)));
            }
            if !s.origin.is_empty() {
                out.push_str(&format!("    // Origin:      {}\n", escape_line_comment(&s.origin)));
            }
            out.push_str(&format!("    const CODE: &str = {};\n", rust_string(&s.code)));
            out.push_str(&format!(
                "    common::expect_grammar_gap(CODE, {});\n",
                rust_string(&s.origin)
            ));
            out.push_str("}\n\n");
        }
    }

    let dest = out_dir.join("localized_gaps_generated.rs");
    fs::write(&dest, out).expect("write localized_gaps_generated.rs");
}

fn escape_line_comment(s: &str) -> String {
    s.replace('\n', " ⏎ ").replace('\r', "")
}

// ─── Utilities ──────────────────────────────────────────────────────

fn sanitize(name: &str) -> String {
    let mut out = String::new();
    for c in name.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_lowercase());
        } else {
            out.push('_');
        }
    }
    let trimmed = out.trim_matches('_').to_string();
    let squeezed = {
        let mut s = String::new();
        let mut last_underscore = false;
        for c in trimmed.chars() {
            if c == '_' {
                if !last_underscore {
                    s.push('_');
                }
                last_underscore = true;
            } else {
                s.push(c);
                last_underscore = false;
            }
        }
        s
    };
    if squeezed.is_empty() || squeezed.chars().next().unwrap().is_ascii_digit() {
        format!("n{squeezed}")
    } else {
        squeezed
    }
}

fn unique_ident(used: &mut HashSet<String>, base: &str) -> String {
    if used.insert(base.to_string()) {
        return base.to_string();
    }
    let mut i = 2;
    loop {
        let candidate = format!("{base}_{i}");
        if used.insert(candidate.clone()) {
            return candidate;
        }
        i += 1;
    }
}

/// Emit a Rust string literal (double-quoted, with escapes). Keeps generated
/// code readable without pulling in an extra escaping crate.
fn rust_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\0' => out.push_str("\\0"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{{{:x}}}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
